name: Build and Push Docker image # Nome do workflow

on:
  push:
    branches:
      - main # Roda toda vez que der push na branch main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        # Baixa o código do repositório pra poder trabalhar com ele

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        # Prepara o ambiente Docker

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }} # Pega seu usuário Docker Hub dos secrets
          password: ${{ secrets.DOCKERHUB_TOKEN }} # Pega o token pra autenticar

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: . # Contexto do build
          push: true # Fazer o push da imagem depois que buildar
          tags: julianofsz/appmenu-backend:latest # Troque o "julianofsz" pelo seu usuario do docker
